apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cronwf-dag
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 70
  workflowSpec:
    entrypoint: dag-template
    templates:
    - name: dag-template
      dag:
        tasks:
        - name: Task1
          template: task-template
        - name: Task2
          template: task-template
          dependencies: [Task1]
        - name: Task3
          template: task-template
          dependencies: [Task1]
        - name: Task4
          template: task-template
          dependencies: [Task2, Task3]
  
    - name: task-template
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          print("Task executed. Changed. Change again. ")