apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-condition
spec:
  entrypoint: dag-template
  arguments:
    parameters:
    - name: messageA
      value: A
    - name: messageB
      value: B

  templates:
  - name: dag-template
    inputs:
      parameters:
      - name: messageA
      - name: messageB

    dag:
      tasks:
      - name: Task1
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.messageA}}" }]
        template: task-decision
      - name: TaskA
        template: task-A
        dependencies: [Task1]
        when: "{{tasks.Task1.outputs.result}} == A"
      - name: TaskB
        template: task-B
        dependencies: [Task1]
        when: "{{tasks.Task1.outputs.result}} == B"
      - name: Task2
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.messageB}}" }]
        template: task-decision
      - name: TaskA2
        template: task-A
        dependencies: [Task2]
        when: "{{tasks.Task2.outputs.result}} == A"
      - name: TaskB2
        template: task-B
        dependencies: [Task2]
        when: "{{tasks.Task2.outputs.result}} == B"
    
  - name: task-decision
    inputs:
      parameters:
      - name: text
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        p = "{{inputs.parameters.text}}"
        print(p)

  - name: task-A
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task A was executed.")

  - name: task-B
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task B was executed.")